### ISSUE TITLE
Error on Email Reply

### ISSUE THREAD

**Issue by yaitsbilly** [Yoruio/Membarr#45]
I'm getting this error when I reply to the bot with a email, bot messages the user when a role it added just fine and no start up errors.

[2023-07-09 17:07:58] [ERROR   ] discord.client: Ignoring exception in on_member_update
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "C:\Program Files\Invite Membarr\app\bot\cogs\app.py", line 273, in on_member_update
    email = await self.getemail(after)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Invite Membarr\app\bot\cogs\app.py", line 162, in getemail
    await embedinfo(after,'    ')
  File "C:\Program Files\Invite Membarr\app\bot\helper\message.py", line 10, in embedinfo
    await send_embed(recipient, embed, ephemeral)
  File "C:\Program Files\Invite Membarr\app\bot\helper\message.py", line 26, in send_embed
    await recipient.send(embed=embed)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\discord\abc.py", line 1561, in send
    data = await state.http.send_message(channel.id, params=params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\discord\http.py", line 744, in request
    raise HTTPException(response, data)
discord.errors.HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
In embeds.0.description: This field is required

**Comment by yaitsbilly** [comment]
Fixed, grabbed an updated app.py file from here.
